### ISSUE TITLE
Forgot to fix this, still need a hand?

### ISSUE THREAD

**Issue by ghost** [jcwren/3dprinting#1]
Hey, I originally commented on Facebook that I would take a look at your file for toy, the cup holder, to see what's going on with the top layer for you.

If ya still need help with the file, I'm more then happy to help. Sorry  I forgot to take a look at it the other day. I can do so this morning and will post a fix here for you.

**Comment by ghost** [comment]
For you*

**Comment by jcwren** [comment]
Yah, it would be great if you could. I'd really like to understand why it's not filling it in.
